In [1]:
import pandas as pd
data =pd.read_csv("Amazon_Unlocked_Mobile.csv", header = 0) 

# Reading the dataset

In [2]:
df=pd.DataFrame(data)
print (df[:5])

                                        Product Name Brand Name   Price  \
0  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
1  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
2  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
3  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   
4  "CLEAR CLEAN ESN" Sprint EPIC 4G Galaxy SPH-D7...    Samsung  199.99   

   Rating                                            Reviews  Review Votes  
0       5  I feel so LUCKY to have found this used (phone...           1.0  
1       4  nice phone, nice up grade from my pantach revu...           0.0  
2       5                                       Very pleased           0.0  
3       4  It works good but it goes slow sometimes but i...           0.0  
4       4  Great phone to replace my lost phone. The only...           0.0  


# Storing all the reviews and their labels

In [3]:
all_reviews=[]
for i in range(len(data['Reviews'])):
    r=str(data['Reviews'][i])
    all_reviews.append(r)
    
all_labels=[]
for r in data['Rating']:
    if r>=3:
        all_labels.append(1)
    else:
        all_labels.append(0)
#all_labels=data['Rating']
#all_labels=all_labels.tolist()

print ("Shape of reviews: ", type(all_reviews))
print ("Shape of labels: ", type(all_labels))

print ("Total no of reviews: ", len(all_reviews))
print ("Total no of labels: ", len(all_labels))

Shape of reviews:  <class 'list'>
Shape of labels:  <class 'list'>
Total no of reviews:  413840
Total no of labels:  413840


In [4]:
print (all_reviews[0])
print (all_labels[0])

I feel so LUCKY to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. My Son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! Thank you Seller, we really appreciate it & your honesty re: said used phone.I recommend this seller very highly & would but from them again!!
1


# Pre-processing

In [5]:
#converting the reviews into lower cases
all_reviews = [item.lower() for item in all_reviews]


In [8]:
from string import punctuation
all_text = ''.join([c for c in all_reviews if c not in punctuation])

In [9]:
print(all_reviews[0])

i feel so lucky to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. my son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! thank you seller, we really appreciate it & your honesty re: said used phone.i recommend this seller very highly & would but from them again!!


In [10]:
from string import punctuation
all_text = '\n'.join([c for c in all_reviews])

In [11]:
print(all_text[:500])

i feel so lucky to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. my son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! thank you seller, we really appreciate it & your honesty re: said used phone.i recommend this seller very highly & would but from them again!!
nice phone, nice up grade from my pantach revue. very clean set up and easy set up. never had an android phone but they are f


In [12]:
reviews_split = all_text.split('\n')
print (reviews_split[:2])

["i feel so lucky to have found this used (phone to us & not used hard at all), phone on line from someone who upgraded and sold this one. my son liked his old one that finally fell apart after 2.5+ years and didn't want an upgrade!! thank you seller, we really appreciate it & your honesty re: said used phone.i recommend this seller very highly & would but from them again!!", 'nice phone, nice up grade from my pantach revue. very clean set up and easy set up. never had an android phone but they are fantastic to say the least. perfect size for surfing and social media. great phone samsung']


In [13]:
all_text = ' '.join(reviews_split)
# create a list of words
words = all_text.split()


In [14]:
words[:500]

['i',
 'feel',
 'so',
 'lucky',
 'to',
 'have',
 'found',
 'this',
 'used',
 '(phone',
 'to',
 'us',
 '&',
 'not',
 'used',
 'hard',
 'at',
 'all),',
 'phone',
 'on',
 'line',
 'from',
 'someone',
 'who',
 'upgraded',
 'and',
 'sold',
 'this',
 'one.',
 'my',
 'son',
 'liked',
 'his',
 'old',
 'one',
 'that',
 'finally',
 'fell',
 'apart',
 'after',
 '2.5+',
 'years',
 'and',
 "didn't",
 'want',
 'an',
 'upgrade!!',
 'thank',
 'you',
 'seller,',
 'we',
 'really',
 'appreciate',
 'it',
 '&',
 'your',
 'honesty',
 're:',
 'said',
 'used',
 'phone.i',
 'recommend',
 'this',
 'seller',
 'very',
 'highly',
 '&',
 'would',
 'but',
 'from',
 'them',
 'again!!',
 'nice',
 'phone,',
 'nice',
 'up',
 'grade',
 'from',
 'my',
 'pantach',
 'revue.',
 'very',
 'clean',
 'set',
 'up',
 'and',
 'easy',
 'set',
 'up.',
 'never',
 'had',
 'an',
 'android',
 'phone',
 'but',
 'they',
 'are',
 'fantastic',
 'to',
 'say',
 'the',
 'least.',
 'perfect',
 'size',
 'for',
 'surfing',
 'and',
 'social',
 'med

# Tokenizing the reviews

In [15]:
from collections import Counter

## Build a dictionary that maps words to integers
counts = Counter(words)
vocab = sorted(counts, key=counts.get, reverse=True)
vocab_to_int = {word: ii for ii, word in enumerate(vocab, 1)}

## use the dict to tokenize each review in reviews_split
## store the tokenized reviews in reviews_ints
reviews_ints = []
for review in reviews_split:
    reviews_ints.append([vocab_to_int[word] for word in review.split()])

In [16]:
# stats about vocabulary
print('Unique words: ', len((vocab_to_int)))
print()

# print tokens in first review
print('Tokenized review: \n', reviews_ints[:1])

Unique words:  222847

Tokenized review: 
 [[2, 304, 24, 2467, 6, 20, 256, 9, 102, 8037, 6, 322, 255, 14, 102, 260, 42, 16682, 7, 19, 777, 33, 440, 205, 1006, 3, 678, 9, 330, 13, 566, 573, 463, 171, 35, 17, 548, 1251, 1749, 67, 135358, 434, 3, 126, 128, 39, 57166, 295, 21, 1192, 132, 58, 1832, 5, 255, 83, 7378, 27659, 222, 102, 1621, 123, 9, 153, 23, 443, 255, 45, 18, 33, 160, 5979]]


In [17]:
import numpy as np
encoded_labels=np.array(all_labels)
print (len(encoded_labels))

413840


# Checking for outliers

In [18]:
# outlier review stats
review_lens = Counter([len(x) for x in reviews_ints])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))

Zero-length reviews: 0
Maximum review length: 5313


# Padding the review tokens

In [19]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [20]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_ints, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_ints), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
print(features[:30,:10])

[[   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0

# Splitting of Data

In [21]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(331072, 200) 
Validation set: 	(41384, 200) 
Test set: 		(41384, 200)


In [22]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 100

# make sure the SHUFFLE your training data
train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size, drop_last=True)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size, drop_last=True)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size, drop_last=True)

In [23]:
# obtain one batch of training data
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([100, 200])
Sample input: 
 tensor([[     0,      0,      0,  ...,     20,      1,   8223],
        [     0,      0,      0,  ...,     12,   3919, 188511],
        [     0,      0,      0,  ...,      0,     26,     94],
        ...,
        [     0,      0,      0,  ...,    177,   3862,   1097],
        [  6236,   4972,    391,  ...,      8,   5150,      9],
        [     0,      0,      0,  ...,    108,     57,  10450]],
       dtype=torch.int32)

Sample label size:  torch.Size([100])
Sample label: 
 tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 1], dtype=torch.int32)


In [24]:
# First checking if GPU is available
train_on_gpu=torch.cuda.is_available()

if(train_on_gpu):
    print('Training on GPU.')
else:
    print('No GPU available, training on CPU.')

Training on GPU.


# Class Defination

In [25]:
import torch.nn as nn

class SentimentRNN(nn.Module):
    """
    The RNN model that will be used to perform Sentiment analysis.
    """

    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        """
        Initialize the model by setting up the layers.
        """
        super(SentimentRNN, self).__init__()

        self.output_size = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        # embedding and GRU layers
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.gru = nn.GRU(embedding_dim, hidden_dim, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        # dropout layer
        self.dropout = nn.Dropout(0.3)
        
        # linear and sigmoid layers
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sig = nn.Sigmoid()
        

    def forward(self, x, hidden):
        """
        Perform a forward pass of our model on some input and hidden state.
        """
        batch_size = x.size(0)

        # embeddings and gru_out
        x = x.long()
        embeds = self.embedding(x)
        gru_out, hidden = self.gru(embeds,hidden)
    
        # stack up lstm outputs
        gru_out = gru_out.contiguous().view(-1, self.hidden_dim)
        
        # dropout and fully-connected layer
        out = self.dropout(gru_out)
        out = self.fc(out)
        # sigmoid function
        sig_out = self.sig(out)
        
        # reshape to be batch_size first
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1] # get last batch of labels
        
        # return last sigmoid output and hidden state
        return sig_out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x hidden_dim,
        # initialized to zero, for hidden state GRU
        weight = next(self.parameters()).data
        
        
        if (train_on_gpu):
            hidden = weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().cuda()
        else:
            hidden = weight.new(self.n_layers, batch_size, self.hidden_dim).zero_()
        
        return hidden
        

In [26]:
# Instantiate the model w/ hyperparams
vocab_size = len(vocab_to_int)+1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2

net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)

print(net)

SentimentRNN(
  (embedding): Embedding(222848, 400)
  (gru): GRU(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sig): Sigmoid()
)


In [27]:
# loss and optimization functions
lr=0.001

criterion = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)


# Training

In [28]:
# training params

epochs = 4 # 3-4 is approx where I noticed the validation loss stop decreasing

counter = 0
print_every = 500
clip=5 # gradient clipping

# move model to GPU, if available
if(train_on_gpu):
    net.cuda()

net.train()
# train for some number of epochs
for e in range(epochs):
    # initialize hidden state
    h = net.init_hidden(batch_size)

    # batch loop
    for inputs, labels in train_loader:
        counter += 1

        if(train_on_gpu):
            inputs, labels = inputs.cuda(), labels.cuda()

        # Creating new variables for the hidden state, otherwise
        # we'd backprop through the entire training history
        h = h.data

        # zero accumulated gradients
        net.zero_grad()

        # get the output from the model
        output, h = net(inputs, h)

        # calculate the loss and perform backprop
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()

        # loss stats
        if counter % print_every == 0:
           
            # Get validation loss
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:

                # Creating new variables for the hidden state, otherwise
                # we'd backprop through the entire training history
                val_h = val_h.data

                if(train_on_gpu):
                    inputs, labels = inputs.cuda(), labels.cuda()

                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())

                val_losses.append(val_loss.item())

            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/4... Step: 500... Loss: 0.178328... Val Loss: 0.200680
Epoch: 1/4... Step: 1000... Loss: 0.157685... Val Loss: 0.183963
Epoch: 1/4... Step: 1500... Loss: 0.141219... Val Loss: 0.175572
Epoch: 1/4... Step: 2000... Loss: 0.099997... Val Loss: 0.175724
Epoch: 1/4... Step: 2500... Loss: 0.185268... Val Loss: 0.175142
Epoch: 1/4... Step: 3000... Loss: 0.166621... Val Loss: 0.174952
Epoch: 2/4... Step: 3500... Loss: 0.117700... Val Loss: 0.187670
Epoch: 2/4... Step: 4000... Loss: 0.068774... Val Loss: 0.191127
Epoch: 2/4... Step: 4500... Loss: 0.083639... Val Loss: 0.213521
Epoch: 2/4... Step: 5000... Loss: 0.115473... Val Loss: 0.199444
Epoch: 2/4... Step: 5500... Loss: 0.153099... Val Loss: 0.203858
Epoch: 2/4... Step: 6000... Loss: 0.067007... Val Loss: 0.198537
Epoch: 2/4... Step: 6500... Loss: 0.097363... Val Loss: 0.192809
Epoch: 3/4... Step: 7000... Loss: 0.101037... Val Loss: 0.231498
Epoch: 3/4... Step: 7500... Loss: 0.050835... Val Loss: 0.235143
Epoch: 3/4... Step: 8000..

# Testing

In [29]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h=h.data

    if(train_on_gpu):
        inputs, labels = inputs.cuda(), labels.cuda()
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 0.350
Test accuracy: 0.904
